### ISSUE TITLE
能告诉下你的联系方式吗？

### ISSUE THREAD

**Issue by Object-Ping** [nailperry-zd/CodelessDA-Gradle-Plugin#2]
例如：QQ

**Comment by nailperry-zd** [comment]
QQ我不常用的，就用邮箱联系吧，邮箱经常使用的zhangdan_only@163.com
发自网易邮箱大师
在2017年04月14日 13:39，PingWang 写道： 例如：QQ

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nailperry-zd/CodelessDA-Gradle-Plugin","title":"nailperry-zd/CodelessDA-Gradle-Plugin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nailperry-zd/CodelessDA-Gradle-Plugin"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"能告诉下你的联系方式吗？ (#2)"}],"action":{"name":"View Issue","url":"https://github.com/nailperry-zd/CodelessDA-Gradle-Plugin/issues/2"}}}
